#!/usr/bin/env bash

# Colors
RESET="\e[0m"
RED="\e[31m"
YELLOW="\e[1;33m"
GREEN="\e[32m"

if [ "$EUID" -ne 0 ]
  then echo -e "${RED}Please run the setup as root${RESET}"
  exit
fi

content=$(curl https://raw.githubusercontent.com/vclemenzi/miaofetch/main/bin/miaofetch) # Get content
echo -e "Fetched github repository ${YELLOW}vclemenzi/miaofetch${RESET}"

touch /usr/bin/miaofetch # Create file
echo -e "Created file ${YELLOW}miaofetch${RESET}"

echo "$content" > /usr/bin/miaofetch # Write file
echo -e "Wrote the file ${YELLOW}miofetch${RESET}"

chmod +x /usr/bin/miaofetch # Give permission
echo -e "${GREEN}miofetch is now installed! Restart terminal and write 'miofetch'${RESET}"
