#!/usr/bin/env bash

touch /usr/local/bin/miaofetch
content=$(curl https://raw.githubusercontent.com/aThebigbot/miaofetch/main/bin/miaofetch)
echo "$content" > /usr/local/bin/miaofetch
chmod +x /usr/local/bin/miaofetch
